version: '3'

services:
  componentui-next:
    container_name: ${CONTAINER_NEXT_NAME}
    build: ./${BUILD_PATH_NEXT_NAME}
    volumes: 
      - ./${PATH_NEXT_NAME}:/home/app/${APP_NEXT_NAME}/
      - ./${BUILD_PATH_NEXT_NAME}/entrypoint-compose.sh:/entrypoint-compose.sh
      #- node_modules_componentio_frontend:/home/app/${APP_FRONTEND_NAME}/node_modules/
    ports:
      - "${PORT_NEXT}:3000"
    entrypoint: "/entrypoint-compose.sh"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  componentui-backend:
    container_name: ${CONTAINER_BACKEND_NAME}
    build: ./${PATH_BACKEND_NAME}
    volumes: 
      - ./${PATH_BACKEND_NAME}:/home/app/${APP_BACKEND_NAME}/
      - ./${PATH_BACKEND_NAME}/entrypoint-compose.sh:/entrypoint-compose.sh
      #- node_modules_componentio_backend:/home/app/${APP_BACKEND_NAME}/node_modules/
    ports:
      - "${PORT_BACKEND}:3000"
    entrypoint: "/entrypoint-compose.sh"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DB_SERVER=mongodb://mongo/${DB_NAME}
      - DB_SERVER_TEST=mongodb://mongo/${DB_NAME_TEST}
      - DB_NAME=${DB_NAME}
      - DB_NAME_TEST=${DB_NAME_TEST}
      - SENTRY_PATH=${SENTRY_EXPRESS}

  mongo:
    image: mongo
    container_name: ${CONTAINER_DB}
    #restart: always
    ports:
      - ${PORT_DB}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: ${CONTAINER_DB_ADMIN}
    #restart: always
    ports:
      - ${PORT_DB_ADMIN}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}