FROM node:12.13.1-alpine3.10

ENV PATH_APP /home/app/
ENV NAME_APP your_next
ENV FULL_PATH ${PATH_APP}${NAME_APP}
ENV ENTRY_POINT_SERVER ${FULL_PATH}/package.json
WORKDIR ${FULL_PATH}/

COPY ./${NAME_APP} .

RUN apk add --update bash
RUN apk add --update nano

WORKDIR ${PATH_APP}/
RUN if [ ! -e ${ENTRY_POINT_SERVER} ]; then npx create-next-app ${NAME_APP} ; fi
WORKDIR ${FULL_PATH}/